[package]
name = "zpool_exporter"
version = "0.3.0"
authors = ["Maxwell L-T <maxwell.lt@live.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
structopt = "0.3.26"
anyhow = "1.0.69"
